## @section Kubernetes settings
##
image:
  ## @param image.registry transmission image registry
  ##
  registry: docker.io
  ## @param image.repository transmission image repository
  ##
  repository: digrouz/transmission
  ##
  ## @param image.tag transmission image tag
  ## Ref: https://hub.docker.com/r/digrouz/transmission/tags
  ##
  tag: "latest"
  ## @param image.pullPolicy transmission image pull policy
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
## @param fullnameOverride String to override the application name.
##
fullnameOverride: ""
## @section Service Configuration
##
service:
  ## @param service.uid user id running transmission
  ##
  uid: 12345
  ## @param service.gid group id running transmission
  ##
  gid: 12345
  ## @param service.autoupgrade apply OS updates inside container at startup
  ##
  autoupgrade: 0
  ## @param service.tz Time Zone
  ##
  tz: Europe/Brussels
  ## @param service.notiftype Notification type
  ## Example: mail, telegram
  ##
  notiftype: "mail"
  ## @param service.umask Umask for created files and directories
  ## Example: 002, 022
  ##
  umask: "002"
## @section SMTP Configuration
##
smtp:
  ## @param smtp.host SMTP host
  ##
  host: ""
  ## @param smtp.from SMTP sender email address
  ## Example: foo.bar@domain.com
  ##
  from: ""
  ## @param smtp.domain SMTP sender email address
  ## Example: domain.com
  ##
  domain: ""
## @section Ingress Configuration
##
ingress:
  ## @param ingress.webui.ingressClassName Ingress class name for transmission ingress
  ##
  ingressClassName: traefik
  ## @param Ingress configuration for transmission webui
  ##
  webui:
    ## @param ingress.webui.enabled Enable ingress for transmission webui
    ##
    enabled: true
    ## @param ingress.webui.host Host for transmission webui ingress
    ##
    host: ""
    ## @param ingress.webui.tls Enable TLS for transmission webui ingress
    ##
    tls: true
    ## @param ingress.webui.annotations Annotations for transmission webui ingress
    ##
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: [] 
      cert-manager.io/cluster-issuer: letsencrypt-prod
  ## @param Ingress configuration for transmission DHT UDP ingress
  ##
  dht:
    ## @param ingress.dht.enabled Enable ingress for transmission DHT UDP
    ##
    enabled: false
    ## @param ingress.dht.traefik.entrypoint Traefik entrypoint for transmission DHT UDP ingress
    ##
    traefik:
      entrypoint: udp-dht
    ## @param ingress.dht.weight Weight for transmission DHT UDP ingress
    ##
    weight: 10
  ## @param Ingress configuration for transmission API TCP ingress
  ##
  api:
    ## @param ingress.api.enabled Enable ingress for transmission API TCP
    ##
    enabled: false
    ## @param ingress.api.traefik.entrypoint Traefik entrypoint for transmission API TCP ingress
    ##
    traefik:
      entrypoint: tcp-api
    ## @param ingress.api.weight Weight for transmission API TCP ingress
    ##
    weight: 10
## @section Storage persistence Configuration
##
persistence:
  config:
    ## @param persistence.config.type Type of persistence for transmission config
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for transmission config using a persistent volume claim
    ##
    pvc:
      ## @param persistence.config.pvc.storageClass Storage class for transmission config
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.config.pvc.existingClaim Existing persistent volume claim for transmission config
      ## If set, the config will be stored in the existing persistent volume claim
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.config.pvc.size Size of the persistent volume for transmission config
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for transmission config using NFS
    ##      
    nfs:
      ## @param persistence.config.nfs.server NFS server for transmission config
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.config.nfs.path NFS path for transmission config
      ## If not set, the default NFS path will be used
      ##
      path: ""
  downloads:
    ## @param persistence.downloads.type Type of persistence for transmission downloads
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for transmission downloads using a persistent volume claim
    ##
    pvc:
      ## @param persistence.downloads.pvc.storageClass Storage class for transmission downloads
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.downloads.pvc.accessMode Access mode for transmission downloads
      ## If not set, the default access mode will be used
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.downloads.pvc.size Size of the persistent volume for transmission downloads
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for transmission downloads using NFS
    ##      
    nfs:
      ## @param persistence.downloads.nfs.server NFS server for transmission downloads
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.downloads.nfs.path NFS path for transmission downloads
      ## If not set, the default NFS path will be used
      ##
      path: ""
  watch:
    ## @param persistence.watch.type Type of persistence for transmission watch
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for transmission watch using a persistent volume claim
    ##
    pvc:
      ## @param persistence.watch.pvc.storageClass Storage class for transmission watch
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.watch.pvc.accessMode Access mode for transmission watch
      ## If not set, the default access mode will be used
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.watch.pvc.size Size of the persistent volume for transmission watch
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for transmission watch using NFS
    ##      
    nfs:
      ## @param persistence.watch.nfs.server NFS server for transmission watch
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.tvshows.nfs.path NFS path for transmission tvshows
      ## If not set, the default NFS path will be used
      ##
      path: ""
  ## Extra volumes to be mounted into the Pod
  ## Example:
  ## extraVolumes:
  ##   - name: my-config
  ##     configMap:
  ##       name: my-configmap
  extraVolumes: []
  ## Extra volumeMounts to add to the transmission container
  ## Example:
  ## extraVolumeMounts:
  ##   - name: my-config
  ##     mountPath: /etc/my-config
  extraVolumeMounts: []
extraObjects: []



