---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-transmission
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: transmission
  template:
    metadata:
      labels:
        app.kubernetes.io/component: transmission
    spec:
      containers:
        - name: transmission
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9091
            - containerPort: 9092
          volumeMounts:
            - mountPath: /config
              name: transmission-config
            - mountPath: /downloads
              name: transmission-downloads
            - mountPath: /watch
              name: transmission-watch
{{- if .Values.persistence.extraVolumeMounts }}
{{- toYaml .Values.persistence.extraVolumeMounts | nindent 12 }}
{{- end }}
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
            - name: DOCKNOTIFTYPE
              value: "{{ .Values.service.notiftype }}"
            - name: DOCKRELAY
              value: "{{ .Values.smtp.host }}"
            - name: DOCKMAIL
              value: "{{ .Values.smtp.to }}"
            - name: DOCKMAILDOMAIN
              value: "{{ .Values.smtp.domain }}"
            - name: DOCKUMASK
              value: "{{ .Values.service.umask | default "002" }}"
            - name: DOCKBLOCKLISTENABLED
              value: "{{ .Values.service.blocklistenabled | default "false" }}"
            - name: DOCKBLOCKLISTURL
              value: "{{ .Values.service.blocklisturl | default "http://list.iblocklist.org/?list=bt_level1&fileformat=p2p&archiveformat=gz" }}"
            - name: DOCKRPCENABLED
              value: "{{ .Values.service.rpcenabled | default "true" }}"
            - name: DOCKRPCAUTHENTICATIONREQUIRED
              value: "{{ .Values.service.rpcauthenticationrequired | default "true" }}"
            - name: DOCKRPCUSERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rpc-secret
                  key: rpc-username
            - name: DOCKRPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rpc-secret
                  key: rpc-password
            - name: DOCKRPCPORT
              value: "{{ .Values.service.rpcport | default "9092" }}"
            - name: DOCKRPCBINDADDRESS
              value: "{{ .Values.service.rpcbindaddress | default "0.0.0.0" }}"
            - name: DOCKRPCWHITELISTENABLED
              value: "{{ .Values.service.rpcwhitelistenabled | default "false" }}"
            - name: DOCKRPCWHITELIST
              value: "{{ .Values.service.rpcwhitelist | default "127.0.0.1,::1" }}"
            - name: DOCKRPCHOSTWHITELISTENABLED
              value: "{{ .Values.service.rpchostwhitelistenabled | default "false" }}"
            - name: DOCKRPCHOSTWHITELIST
              value: "{{ .Values.service.rpchostwhitelist | default "127.0.0.1,::1" }}"
      volumes:
        - name: transmission-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: transmission-downloads
          {{- if eq .Values.persistence.downloads.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads-pvc
          {{- else if eq .Values.persistence.downloads.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.downloads.nfs.server }}
            path: {{ .Values.persistence.downloads.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: transmission-watch
          {{- if eq .Values.persistence.watch.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-watch-pvc
          {{- else if eq .Values.persistence.watch.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.watch.nfs.server }}
            path: {{ .Values.persistence.watch.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
{{- if .Values.persistence.extraVolumes }}
{{- toYaml .Values.persistence.extraVolumes | nindent 8 }}
{{- end }}
