---
{{- if .Values.ingress.webui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: transmission
  {{- if .Values.ingress.webui.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.webui.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.webui.ingressClassName }}
  ingressClassName: {{ .Values.ingress.webui.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.webui.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              name: webui
  {{- if .Values.ingress.webui.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.webui.host }}
      secretName: {{ .Values.ingress.webui.host }}-tls
  {{- end }}
{{- end }}
{{- if .Values.ingress.dht.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ .Release.Name }}-dht-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.dht.traefik.entrypoint }}
  routes:
  - services:
    - name: {{ .Release.Name }}-svc
      port:  9092
      weight: {{ .Values.ingress.dht.weight }}
{{- end }}
---
{{- if .Values.ingress.api.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-api-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
spec:
  entryPoints:
    - {{ .Values.ingress.api.traefik.entrypoint }}
  routes:
  - match: HostSNI(`*`)
    priority: {{ .Values.ingress.api.priority }}
    services:
    - name: {{ .Release.Name }}-svc
      port:  9092
{{- end }}