apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rpc-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rpc-username: {{ .Values.service.rpcusername | default "transmission" | b64enc }}
  rpc-password: {{ .Values.service.rpcpassword | default "transmission" | b64enc }}