apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-rpc-secret
type: Opaque
data:
  rpc-username: {{ .Values.service.rpcusername | default "transmission" | b64enc }}
  rpc-password: {{ .Values.service.rpcpassword | default "transmission" | b64enc }}